name: Run Fetch Script

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies for newspaper3k
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt-dev libjpeg-dev zlib1g-dev libffi-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir feedparser requests newspaper3k
          python -c "import nltk; nltk.download('punkt')"
          pip show newspaper3k || (echo "newspaper3k failed to install!" && exit 1)
          pip list

      - name: Run fetch script
        run: python scripts/fetch_news.py