name: Fetch Watch News

on:
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-lxml python3-dev libxml2-dev libxslt-dev libjpeg-dev zlib1g-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests newspaper3k

      - name: Debug: Check installed packages
        run: pip list

      - name: Run fetch script
        run: python scripts/fetch_news.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A  # Stage all changes, including untracked files
          git commit -m "📰 Fetched watch news updates" || echo "No changes to commit"
          git push