name: Run Fetch Script

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev libxml2-dev libxslt-dev libjpeg-dev zlib1g-dev libpng-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir newspaper3k feedparser requests
          python -c "import nltk; nltk.download('punkt')"

      - name: List installed packages  # ✅ Add this step here
        run: pip list

      - name: Verify newspaper installation
        run: |
          pip show newspaper3k
          python -c "from newspaper import Article; print('✅ newspaper module is importable')"

      - name: Run fetch script
        run: python scripts/fetch_news.py