name: Daily News Update

on:
  schedule:
    - cron: "0 8 * * *"  # Runs daily at 8:00 UTC
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-lxml python3-dev libxml2-dev libxslt-dev libjpeg-dev zlib1g-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests newspaper3k

      - name: Run fetch script
        run: python scripts/fetch_news.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .  # Stage all changes, including untracked files
          git commit -m "📰 Daily news update" || echo "No changes to commit"
          git push